<?php

namespace ST\PlatformBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListComments($trick){
        $qb = $this->createQueryBuilder('a');

        $qb->select('a')
            ->where('a.trick = :trick')
            ->orderBy('a.createdAt', 'DESC')
            ->setParameter('trick', $trick);

        return $qb->getQuery();
    }
}
