<?php

namespace ST\PlatformBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeImagesWithoutName($trick){
        $var = '';
        $qb = $this->createQueryBuilder('a');

        $qb->delete()
            ->where('a.trick = :trick')
            ->andWhere('a.imageName = :var')
            ->setParameter('trick', $trick)
            ->setParameter('var', $var);

        $qb->getQuery()->execute();
    }
}
