<?php

namespace ST\PlatformBundle\Repository;

/**
 * TrickGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
